export const COMPANIES = [
  {
    id: 'otoniel',
    cnpj: '01.260.756/0001-32',
    name: 'OTONIEL ANTONIO DOS SANTOS',
    tradeName: 'OTONIEL ANTONIO DOS SANTOS - ME',
    municipalRegistration: '197618',
    address: 'W-5, 159 - RES. MORADA DOS IPES',
    neighborhood: '',
    city: 'GOIANIA',
    state: 'GO',
    zipCode: '74692105',
    phone: '62565351',
    email: 'supremocristina@gmail.com',
  },
  {
    id: 'pedro',
    cnpj: '51.518.502/0001-40',
    name: 'PEDRO OTONIEL DE OLIVEIRA SANTOS',
    tradeName: 'PEDRO OTONIEL DE OLIVEIRA SANTOS ME',
    municipalRegistration: '',
    address: 'Rua 34, 0',
    neighborhood: 'Setor Santos Dumont',
    city: 'Goiânia',
    state: 'GO',
    zipCode: '74463730',
    phone: '62565351',
    email: 'supremocristina@gmail.com',
  },
];
